name: Build Docker Image

# Trigger the workflow on push to main branch and on pull requests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.1
      with:
        fetch-depth: 0

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./src  # Set the context to the src directory where your Dockerfile is located
        file: ./src/dockerfile  # Specify the path to the Dockerfile
        push: true
        tags: 
          ${{ secrets.DOCKER_USERNAME }}/weather-app:${{ github.sha }} 
 
    # - name: Update Kubernetes Deployment YAML
    #   run: |
    #     sed -i 's|image: jhkwon91/weather-app:.*|image: jhkwon91/weather-app:${{ github.sha }}|' ./deployment/deployment.yaml

    # - name: Commit and push changes
    #   run: |
    #     git config --global user.name "GitHub Actions"
    #     git config --local user.email "action@github.com"
    #     git add ./deployment/deployment.yaml
    #     git commit -m "Update image tag to ${{ github.sha }}"
    #     git push https://${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref }}
    
